// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/MassoudJavadi/filmophilia/api/internal/db"
	"github.com/MassoudJavadi/filmophilia/api/internal/handler"
	"github.com/MassoudJavadi/filmophilia/api/internal/service"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

func InitializeServer(dbPool *pgxpool.Pool) *Server {
	queries := db.New(dbPool)
	userService := service.NewUserService(queries)
	userHandler := handler.NewUserHandler(userService)
	server := NewServer(dbPool, userHandler)
	return server
}
