// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/MassoudJavadi/filmophilia/api/internal/db"
	"github.com/MassoudJavadi/filmophilia/api/internal/handler"
	"github.com/MassoudJavadi/filmophilia/api/internal/pkg/oauth"
	"github.com/MassoudJavadi/filmophilia/api/internal/pkg/token"
	"github.com/MassoudJavadi/filmophilia/api/internal/service"
	"github.com/jackc/pgx/v5/pgxpool"
	"os"
)

// Injectors from wire.go:

func InitializeServer(dbPool *pgxpool.Pool) *Server {
	queries := db.New(dbPool)
	jwtManager := provideJWTManager()
	authService := service.NewAuthService(queries, jwtManager)
	googleManager := oauth.NewGoogleManager()
	oAuthService := service.NewOAuthService(queries, authService, googleManager)
	authHandler := handler.NewAuthHandler(authService, oAuthService)
	movieService := service.NewMovieService(queries)
	movieHandler := handler.NewMovieHandler(movieService)
	ratingService := service.NewRatingService(queries)
	ratingHandler := handler.NewRatingHandler(ratingService)
	watchlistService := service.NewWatchlistService(queries)
	watchlistHandler := handler.NewWatchlistHandler(watchlistService)
	commentService := service.NewCommentService(queries)
	commentHandler := handler.NewCommentHandler(commentService)
	reactionService := service.NewReactionService(queries)
	reactionHandler := handler.NewReactionHandler(reactionService)
	userService := service.NewUserService(queries)
	userHandler := handler.NewUserHandler(userService)
	followService := service.NewFollowService(queries)
	followHandler := handler.NewFollowHandler(followService)
	genreService := service.NewGenreService(queries)
	genreHandler := handler.NewGenreHandler(genreService)
	server := NewServer(dbPool, authHandler, movieHandler, ratingHandler, watchlistHandler, commentHandler, reactionHandler, userHandler, followHandler, genreHandler, jwtManager)
	return server
}

// wire.go:

func provideJWTManager() *token.JWTManager {
	secret := os.Getenv("JWT_SECRET")
	if secret == "" {
		secret = "dev-secret-change-in-production"
	}
	return token.NewJWTManager(secret)
}
