// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/MassoudJavadi/filmophilia/api/internal/db"
	"github.com/MassoudJavadi/filmophilia/api/internal/handler"
	"github.com/MassoudJavadi/filmophilia/api/internal/pkg/config"
	"github.com/MassoudJavadi/filmophilia/api/internal/pkg/oauth"
	"github.com/MassoudJavadi/filmophilia/api/internal/pkg/ratelimit"
	"github.com/MassoudJavadi/filmophilia/api/internal/pkg/token"
	"github.com/MassoudJavadi/filmophilia/api/internal/service"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

func InitializeServer(dbPool *pgxpool.Pool) *Server {
	config := provideConfig()
	queries := db.New(dbPool)
	jwtManager := provideJWTManager(config)
	authService := service.NewAuthService(queries, jwtManager)
	googleManager := oauth.NewGoogleManager()
	oAuthService := service.NewOAuthService(queries, authService, googleManager)
	authHandler := handler.NewAuthHandler(authService, oAuthService)
	movieService := service.NewMovieService(queries)
	movieHandler := handler.NewMovieHandler(movieService)
	ratingService := service.NewRatingService(queries)
	ratingHandler := handler.NewRatingHandler(ratingService)
	watchlistService := service.NewWatchlistService(queries)
	watchlistHandler := handler.NewWatchlistHandler(watchlistService)
	commentService := service.NewCommentService(queries)
	commentHandler := handler.NewCommentHandler(commentService)
	reactionService := service.NewReactionService(queries)
	reactionHandler := handler.NewReactionHandler(reactionService)
	userService := service.NewUserService(queries)
	userHandler := handler.NewUserHandler(userService)
	followService := service.NewFollowService(queries)
	followHandler := handler.NewFollowHandler(followService)
	genreService := service.NewGenreService(queries)
	genreHandler := handler.NewGenreHandler(genreService)
	activityService := service.NewActivityService(queries)
	activityHandler := handler.NewActivityHandler(activityService)
	notificationService := service.NewNotificationService(queries)
	notificationHandler := handler.NewNotificationHandler(notificationService)
	rateLimiter := provideRateLimiter()
	ratelimitConfig := provideRateLimitConfig()
	server := NewServer(dbPool, config, authHandler, movieHandler, ratingHandler, watchlistHandler, commentHandler, reactionHandler, userHandler, followHandler, genreHandler, activityHandler, notificationHandler, jwtManager, rateLimiter, ratelimitConfig)
	return server
}

// wire.go:

func provideConfig() config.Config {
	return config.Load()
}

func provideJWTManager(cfg config.Config) *token.JWTManager {
	return token.NewJWTManager(cfg.JWTSecret)
}

func provideRateLimiter() *ratelimit.RateLimiter {
	client := ratelimit.NewRedisClient()
	return ratelimit.NewRateLimiter(client)
}

func provideRateLimitConfig() ratelimit.Config {
	return ratelimit.LoadFromEnv()
}
