// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFollowingActivities = `-- name: CountFollowingActivities :one
SELECT COUNT(*)::INT as count
FROM activities a
JOIN follows f ON f.following_id = a.user_id
WHERE f.follower_id = $1
`

// Count total activities from users that current user follows
func (q *Queries) CountFollowingActivities(ctx context.Context, followerID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countFollowingActivities, followerID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countUserActivities = `-- name: CountUserActivities :one
SELECT COUNT(*)::INT as count
FROM activities
WHERE user_id = $1
`

// Count total activities for a user
func (q *Queries) CountUserActivities(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countUserActivities, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (user_id, action, entity_type, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, action, entity_type, entity_id, metadata, created_at
`

type CreateActivityParams struct {
	UserID     int32      `json:"user_id"`
	Action     string     `json:"action"`
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
	Metadata   []byte     `json:"metadata"`
}

// Create a new activity entry
func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActivityByEntity = `-- name: DeleteActivityByEntity :exec
DELETE FROM activities
WHERE entity_type = $1 AND entity_id = $2
`

type DeleteActivityByEntityParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
}

// Delete activities related to a specific entity (when entity is deleted)
func (q *Queries) DeleteActivityByEntity(ctx context.Context, arg DeleteActivityByEntityParams) error {
	_, err := q.db.Exec(ctx, deleteActivityByEntity, arg.EntityType, arg.EntityID)
	return err
}

const deleteUserActivities = `-- name: DeleteUserActivities :exec
DELETE FROM activities
WHERE user_id = $1
`

// Delete all activities for a user (cleanup)
func (q *Queries) DeleteUserActivities(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserActivities, userID)
	return err
}

const getActivitiesByEntity = `-- name: GetActivitiesByEntity :many
SELECT a.id, a.user_id, a.action, a.entity_type, a.entity_id, a.metadata, a.created_at,
    u.username,
    u.display_name,
    u.avatar_url
FROM activities a
JOIN users u ON u.id = a.user_id
WHERE a.entity_type = $1 AND a.entity_id = $2
ORDER BY a.created_at DESC
LIMIT $3 OFFSET $4
`

type GetActivitiesByEntityParams struct {
	EntityType EntityType `json:"entity_type"`
	EntityID   int64      `json:"entity_id"`
	Limit      int32      `json:"limit"`
	Offset     int32      `json:"offset"`
}

type GetActivitiesByEntityRow struct {
	ID          int64              `json:"id"`
	UserID      int32              `json:"user_id"`
	Action      string             `json:"action"`
	EntityType  EntityType         `json:"entity_type"`
	EntityID    int64              `json:"entity_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

// Get all activities for a specific entity (e.g., all activities for a movie)
func (q *Queries) GetActivitiesByEntity(ctx context.Context, arg GetActivitiesByEntityParams) ([]GetActivitiesByEntityRow, error) {
	rows, err := q.db.Query(ctx, getActivitiesByEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivitiesByEntityRow
	for rows.Next() {
		var i GetActivitiesByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingActivities = `-- name: GetFollowingActivities :many
SELECT a.id, a.user_id, a.action, a.entity_type, a.entity_id, a.metadata, a.created_at,
    u.username,
    u.display_name,
    u.avatar_url
FROM activities a
JOIN users u ON u.id = a.user_id
JOIN follows f ON f.following_id = a.user_id
WHERE f.follower_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingActivitiesParams struct {
	FollowerID int32 `json:"follower_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type GetFollowingActivitiesRow struct {
	ID          int64              `json:"id"`
	UserID      int32              `json:"user_id"`
	Action      string             `json:"action"`
	EntityType  EntityType         `json:"entity_type"`
	EntityID    int64              `json:"entity_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

// Get activities from users that current user follows (social feed)
func (q *Queries) GetFollowingActivities(ctx context.Context, arg GetFollowingActivitiesParams) ([]GetFollowingActivitiesRow, error) {
	rows, err := q.db.Query(ctx, getFollowingActivities, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingActivitiesRow
	for rows.Next() {
		var i GetFollowingActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivities = `-- name: GetUserActivities :many
SELECT a.id, a.user_id, a.action, a.entity_type, a.entity_id, a.metadata, a.created_at,
    u.username,
    u.display_name,
    u.avatar_url
FROM activities a
JOIN users u ON u.id = a.user_id
WHERE a.user_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserActivitiesParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUserActivitiesRow struct {
	ID          int64              `json:"id"`
	UserID      int32              `json:"user_id"`
	Action      string             `json:"action"`
	EntityType  EntityType         `json:"entity_type"`
	EntityID    int64              `json:"entity_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

// Get activities for a specific user (user's own feed)
func (q *Queries) GetUserActivities(ctx context.Context, arg GetUserActivitiesParams) ([]GetUserActivitiesRow, error) {
	rows, err := q.db.Query(ctx, getUserActivities, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserActivitiesRow
	for rows.Next() {
		var i GetUserActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
