// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentReplies = `-- name: CountCommentReplies :one
SELECT COUNT(*)::INT as count
FROM comments
WHERE parent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCommentReplies(ctx context.Context, parentID pgtype.Int8) (int32, error) {
	row := q.db.QueryRow(ctx, countCommentReplies, parentID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countMovieComments = `-- name: CountMovieComments :one
SELECT COUNT(*)::INT as count
FROM comments
WHERE movie_id = $1 AND parent_id IS NULL AND deleted_at IS NULL
`

func (q *Queries) CountMovieComments(ctx context.Context, movieID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countMovieComments, movieID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (user_id, movie_id, parent_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, movie_id, parent_id, content, like_count, deleted_at, created_at, updated_at
`

type CreateCommentParams struct {
	UserID   pgtype.Int4 `json:"user_id"`
	MovieID  int32       `json:"movie_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
	Content  string      `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.UserID,
		arg.MovieID,
		arg.ParentID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.ParentID,
		&i.Content,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, user_id, movie_id, parent_id, content, like_count, deleted_at, created_at, updated_at FROM comments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCommentByID(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.ParentID,
		&i.Content,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentReplies = `-- name: GetCommentReplies :many
SELECT
    c.id, c.user_id, c.movie_id, c.parent_id, c.content, c.like_count, c.deleted_at, c.created_at, c.updated_at,
    u.username,
    u.display_name,
    u.avatar_url
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.parent_id = $1 AND c.deleted_at IS NULL
ORDER BY c.created_at ASC
LIMIT $2 OFFSET $3
`

type GetCommentRepliesParams struct {
	ParentID pgtype.Int8 `json:"parent_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetCommentRepliesRow struct {
	ID          int64              `json:"id"`
	UserID      pgtype.Int4        `json:"user_id"`
	MovieID     int32              `json:"movie_id"`
	ParentID    pgtype.Int8        `json:"parent_id"`
	Content     string             `json:"content"`
	LikeCount   pgtype.Int4        `json:"like_count"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetCommentReplies(ctx context.Context, arg GetCommentRepliesParams) ([]GetCommentRepliesRow, error) {
	rows, err := q.db.Query(ctx, getCommentReplies, arg.ParentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentRepliesRow
	for rows.Next() {
		var i GetCommentRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MovieID,
			&i.ParentID,
			&i.Content,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentWithUser = `-- name: GetCommentWithUser :one
SELECT
    c.id, c.user_id, c.movie_id, c.parent_id, c.content, c.like_count, c.deleted_at, c.created_at, c.updated_at,
    u.username,
    u.display_name,
    u.avatar_url
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCommentWithUserRow struct {
	ID          int64              `json:"id"`
	UserID      pgtype.Int4        `json:"user_id"`
	MovieID     int32              `json:"movie_id"`
	ParentID    pgtype.Int8        `json:"parent_id"`
	Content     string             `json:"content"`
	LikeCount   pgtype.Int4        `json:"like_count"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetCommentWithUser(ctx context.Context, id int64) (GetCommentWithUserRow, error) {
	row := q.db.QueryRow(ctx, getCommentWithUser, id)
	var i GetCommentWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.ParentID,
		&i.Content,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const getMovieComments = `-- name: GetMovieComments :many
SELECT
    c.id, c.user_id, c.movie_id, c.parent_id, c.content, c.like_count, c.deleted_at, c.created_at, c.updated_at,
    u.username,
    u.display_name,
    u.avatar_url,
    (SELECT COUNT(*) FROM comments r WHERE r.parent_id = c.id AND r.deleted_at IS NULL)::INT as reply_count
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.movie_id = $1
  AND c.parent_id IS NULL
  AND c.deleted_at IS NULL
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMovieCommentsParams struct {
	MovieID int32 `json:"movie_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type GetMovieCommentsRow struct {
	ID          int64              `json:"id"`
	UserID      pgtype.Int4        `json:"user_id"`
	MovieID     int32              `json:"movie_id"`
	ParentID    pgtype.Int8        `json:"parent_id"`
	Content     string             `json:"content"`
	LikeCount   pgtype.Int4        `json:"like_count"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	ReplyCount  int32              `json:"reply_count"`
}

func (q *Queries) GetMovieComments(ctx context.Context, arg GetMovieCommentsParams) ([]GetMovieCommentsRow, error) {
	rows, err := q.db.Query(ctx, getMovieComments, arg.MovieID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovieCommentsRow
	for rows.Next() {
		var i GetMovieCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MovieID,
			&i.ParentID,
			&i.Content,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserComments = `-- name: GetUserComments :many
SELECT
    c.id, c.user_id, c.movie_id, c.parent_id, c.content, c.like_count, c.deleted_at, c.created_at, c.updated_at,
    m.title as movie_title,
    m.slug as movie_slug
FROM comments c
JOIN movies m ON m.id = c.movie_id
WHERE c.user_id = $1 AND c.deleted_at IS NULL
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserCommentsParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetUserCommentsRow struct {
	ID         int64              `json:"id"`
	UserID     pgtype.Int4        `json:"user_id"`
	MovieID    int32              `json:"movie_id"`
	ParentID   pgtype.Int8        `json:"parent_id"`
	Content    string             `json:"content"`
	LikeCount  pgtype.Int4        `json:"like_count"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	MovieTitle string             `json:"movie_title"`
	MovieSlug  string             `json:"movie_slug"`
}

func (q *Queries) GetUserComments(ctx context.Context, arg GetUserCommentsParams) ([]GetUserCommentsRow, error) {
	rows, err := q.db.Query(ctx, getUserComments, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCommentsRow
	for rows.Next() {
		var i GetUserCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MovieID,
			&i.ParentID,
			&i.Content,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MovieTitle,
			&i.MovieSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteComment, id)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, movie_id, parent_id, content, like_count, deleted_at, created_at, updated_at
`

type UpdateCommentParams struct {
	ID      int64  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.ParentID,
		&i.Content,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
