// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*)::INT as count
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.following_id = $1 AND u.status = 'ACTIVE'
`

func (q *Queries) CountFollowers(ctx context.Context, followingID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countFollowers, followingID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*)::INT as count
FROM follows f
JOIN users u ON u.id = f.following_id
WHERE f.follower_id = $1 AND u.status = 'ACTIVE'
`

func (q *Queries) CountFollowing(ctx context.Context, followerID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countFollowing, followerID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const followUser = `-- name: FollowUser :one
INSERT INTO follows (follower_id, following_id)
VALUES ($1, $2)
RETURNING id, follower_id, following_id, created_at
`

type FollowUserParams struct {
	FollowerID  int32 `json:"follower_id"`
	FollowingID int32 `json:"following_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (Follow, error) {
	row := q.db.QueryRow(ctx, followUser, arg.FollowerID, arg.FollowingID)
	var i Follow
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FollowingID,
		&i.CreatedAt,
	)
	return i, err
}

const getFollowers = `-- name: GetFollowers :many
SELECT
    u.id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.bio,
    f.created_at as followed_at
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.following_id = $1 AND u.status = 'ACTIVE'
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowersParams struct {
	FollowingID int32 `json:"following_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

type GetFollowersRow struct {
	ID          int32              `json:"id"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Bio         pgtype.Text        `json:"bio"`
	FollowedAt  pgtype.Timestamptz `json:"followed_at"`
}

func (q *Queries) GetFollowers(ctx context.Context, arg GetFollowersParams) ([]GetFollowersRow, error) {
	rows, err := q.db.Query(ctx, getFollowers, arg.FollowingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowersRow
	for rows.Next() {
		var i GetFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowing = `-- name: GetFollowing :many
SELECT
    u.id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.bio,
    f.created_at as followed_at
FROM follows f
JOIN users u ON u.id = f.following_id
WHERE f.follower_id = $1 AND u.status = 'ACTIVE'
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingParams struct {
	FollowerID int32 `json:"follower_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type GetFollowingRow struct {
	ID          int32              `json:"id"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Bio         pgtype.Text        `json:"bio"`
	FollowedAt  pgtype.Timestamptz `json:"followed_at"`
}

func (q *Queries) GetFollowing(ctx context.Context, arg GetFollowingParams) ([]GetFollowingRow, error) {
	rows, err := q.db.Query(ctx, getFollowing, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingRow
	for rows.Next() {
		var i GetFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
    SELECT 1 FROM follows
    WHERE follower_id = $1 AND following_id = $2
) as is_following
`

type IsFollowingParams struct {
	FollowerID  int32 `json:"follower_id"`
	FollowingID int32 `json:"following_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows
WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  int32 `json:"follower_id"`
	FollowingID int32 `json:"following_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}
