// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: genres.sql

package db

import (
	"context"
)

const countMoviesByGenre = `-- name: CountMoviesByGenre :one
SELECT COUNT(*)::INT as count
FROM movie_genres
WHERE genre_id = $1
`

func (q *Queries) CountMoviesByGenre(ctx context.Context, genreID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countMoviesByGenre, genreID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getAllGenres = `-- name: GetAllGenres :many
SELECT id, name, slug, tmdb_id FROM genres
ORDER BY name
`

func (q *Queries) GetAllGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.Query(ctx, getAllGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.TmdbID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenreByID = `-- name: GetGenreByID :one
SELECT id, name, slug, tmdb_id FROM genres WHERE id = $1
`

func (q *Queries) GetGenreByID(ctx context.Context, id int32) (Genre, error) {
	row := q.db.QueryRow(ctx, getGenreByID, id)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.TmdbID,
	)
	return i, err
}

const getGenreBySlug = `-- name: GetGenreBySlug :one
SELECT id, name, slug, tmdb_id FROM genres WHERE slug = $1
`

func (q *Queries) GetGenreBySlug(ctx context.Context, slug string) (Genre, error) {
	row := q.db.QueryRow(ctx, getGenreBySlug, slug)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.TmdbID,
	)
	return i, err
}

const getGenresForMovie = `-- name: GetGenresForMovie :many
SELECT g.id, g.name, g.slug, g.tmdb_id
FROM genres g
JOIN movie_genres mg ON mg.genre_id = g.id
WHERE mg.movie_id = $1
ORDER BY g.name
`

func (q *Queries) GetGenresForMovie(ctx context.Context, movieID int32) ([]Genre, error) {
	rows, err := q.db.Query(ctx, getGenresForMovie, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.TmdbID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMoviesByGenre = `-- name: GetMoviesByGenre :many
SELECT
    m.id, m.title, m.slug, m.overview, m.poster_url, m.backdrop_url, m.trailer_url, m.release_date, m.runtime, m.content_rating, m.original_language, m.country, m.imdb_id, m.tmdb_id, m.user_avg_rating, m.user_rating_count, m.created_at, m.updated_at, m.imdb_rating, m.rotten_tomatoes, m.metacritic_score, m.letterboxd_rating, m.rating_sum, m.landing_sort_score
FROM movies m
JOIN movie_genres mg ON mg.movie_id = m.id
WHERE mg.genre_id = $1
ORDER BY m.release_date DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetMoviesByGenreParams struct {
	GenreID int32 `json:"genre_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) GetMoviesByGenre(ctx context.Context, arg GetMoviesByGenreParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, getMoviesByGenre, arg.GenreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Overview,
			&i.PosterUrl,
			&i.BackdropUrl,
			&i.TrailerUrl,
			&i.ReleaseDate,
			&i.Runtime,
			&i.ContentRating,
			&i.OriginalLanguage,
			&i.Country,
			&i.ImdbID,
			&i.TmdbID,
			&i.UserAvgRating,
			&i.UserRatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImdbRating,
			&i.RottenTomatoes,
			&i.MetacriticScore,
			&i.LetterboxdRating,
			&i.RatingSum,
			&i.LandingSortScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMoviesByGenreSlug = `-- name: GetMoviesByGenreSlug :many
SELECT
    m.id, m.title, m.slug, m.overview, m.poster_url, m.backdrop_url, m.trailer_url, m.release_date, m.runtime, m.content_rating, m.original_language, m.country, m.imdb_id, m.tmdb_id, m.user_avg_rating, m.user_rating_count, m.created_at, m.updated_at, m.imdb_rating, m.rotten_tomatoes, m.metacritic_score, m.letterboxd_rating, m.rating_sum, m.landing_sort_score
FROM movies m
JOIN movie_genres mg ON mg.movie_id = m.id
JOIN genres g ON g.id = mg.genre_id
WHERE g.slug = $1
ORDER BY m.release_date DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type GetMoviesByGenreSlugParams struct {
	Slug   string `json:"slug"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetMoviesByGenreSlug(ctx context.Context, arg GetMoviesByGenreSlugParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, getMoviesByGenreSlug, arg.Slug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Overview,
			&i.PosterUrl,
			&i.BackdropUrl,
			&i.TrailerUrl,
			&i.ReleaseDate,
			&i.Runtime,
			&i.ContentRating,
			&i.OriginalLanguage,
			&i.Country,
			&i.ImdbID,
			&i.TmdbID,
			&i.UserAvgRating,
			&i.UserRatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImdbRating,
			&i.RottenTomatoes,
			&i.MetacriticScore,
			&i.LetterboxdRating,
			&i.RatingSum,
			&i.LandingSortScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
