// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Department string

const (
	DepartmentDIRECTING      Department = "DIRECTING"
	DepartmentWRITING        Department = "WRITING"
	DepartmentACTING         Department = "ACTING"
	DepartmentPRODUCTION     Department = "PRODUCTION"
	DepartmentCINEMATOGRAPHY Department = "CINEMATOGRAPHY"
	DepartmentEDITING        Department = "EDITING"
	DepartmentSOUND          Department = "SOUND"
	DepartmentART            Department = "ART"
)

func (e *Department) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Department(s)
	case string:
		*e = Department(s)
	default:
		return fmt.Errorf("unsupported scan type for Department: %T", src)
	}
	return nil
}

type NullDepartment struct {
	Department Department `json:"department"`
	Valid      bool       `json:"valid"` // Valid is true if Department is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDepartment) Scan(value interface{}) error {
	if value == nil {
		ns.Department, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Department.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDepartment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Department), nil
}

type EntityType string

const (
	EntityTypeMOVIE   EntityType = "MOVIE"
	EntityTypeREVIEW  EntityType = "REVIEW"
	EntityTypeCOMMENT EntityType = "COMMENT"
	EntityTypeUSER    EntityType = "USER"
)

func (e *EntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntityType(s)
	case string:
		*e = EntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntityType: %T", src)
	}
	return nil
}

type NullEntityType struct {
	EntityType EntityType `json:"entity_type"`
	Valid      bool       `json:"valid"` // Valid is true if EntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.EntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntityType), nil
}

type NotificationType string

const (
	NotificationTypeNEWFOLLOWER      NotificationType = "NEW_FOLLOWER"
	NotificationTypeNEWLIKE          NotificationType = "NEW_LIKE"
	NotificationTypeNEWCOMMENT       NotificationType = "NEW_COMMENT"
	NotificationTypeNEWREVIEW        NotificationType = "NEW_REVIEW"
	NotificationTypeACCOUNTACTIVATED NotificationType = "ACCOUNT_ACTIVATED"
	NotificationTypeACCOUNTSUSPENDED NotificationType = "ACCOUNT_SUSPENDED"
	NotificationTypeACCOUNTBANNED    NotificationType = "ACCOUNT_BANNED"
	NotificationTypeSYSTEMALERT      NotificationType = "SYSTEM_ALERT"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type ReactionType string

const (
	ReactionTypeLIKE  ReactionType = "LIKE"
	ReactionTypeLOVE  ReactionType = "LOVE"
	ReactionTypeLAUGH ReactionType = "LAUGH"
	ReactionTypeSAD   ReactionType = "SAD"
	ReactionTypeANGRY ReactionType = "ANGRY"
)

func (e *ReactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReactionType(s)
	case string:
		*e = ReactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReactionType: %T", src)
	}
	return nil
}

type NullReactionType struct {
	ReactionType ReactionType `json:"reaction_type"`
	Valid        bool         `json:"valid"` // Valid is true if ReactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReactionType) Scan(value interface{}) error {
	if value == nil {
		ns.ReactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReactionType), nil
}

type Role string

const (
	RoleUSER  Role = "USER"
	RoleADMIN Role = "ADMIN"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type UserStatus string

const (
	UserStatusPENDING   UserStatus = "PENDING"
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
	UserStatusBANNED    UserStatus = "BANNED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Account struct {
	ID                int32              `json:"id"`
	UserID            int32              `json:"user_id"`
	Provider          string             `json:"provider"`
	ProviderAccountID string             `json:"provider_account_id"`
	AccessToken       pgtype.Text        `json:"access_token"`
	RefreshToken      pgtype.Text        `json:"refresh_token"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Activity struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	Action     string             `json:"action"`
	EntityType EntityType         `json:"entity_type"`
	EntityID   int32              `json:"entity_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	MovieID   int32              `json:"movie_id"`
	ParentID  pgtype.Int4        `json:"parent_id"`
	Content   string             `json:"content"`
	LikeCount pgtype.Int4        `json:"like_count"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Credit struct {
	ID         int32       `json:"id"`
	MovieID    int32       `json:"movie_id"`
	PersonID   int32       `json:"person_id"`
	Department Department  `json:"department"`
	Role       string      `json:"role"`
	Character  pgtype.Text `json:"character"`
	Order      pgtype.Int4 `json:"order"`
}

type Follow struct {
	ID          int32              `json:"id"`
	FollowerID  int32              `json:"follower_id"`
	FollowingID int32              `json:"following_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Genre struct {
	ID     int32       `json:"id"`
	Name   string      `json:"name"`
	Slug   string      `json:"slug"`
	TmdbID pgtype.Int4 `json:"tmdb_id"`
}

type Movie struct {
	ID               int32              `json:"id"`
	Title            string             `json:"title"`
	Slug             string             `json:"slug"`
	Overview         pgtype.Text        `json:"overview"`
	PosterUrl        pgtype.Text        `json:"poster_url"`
	BackdropUrl      pgtype.Text        `json:"backdrop_url"`
	TrailerUrl       pgtype.Text        `json:"trailer_url"`
	ReleaseDate      pgtype.Date        `json:"release_date"`
	Runtime          pgtype.Int4        `json:"runtime"`
	ContentRating    pgtype.Text        `json:"content_rating"`
	OriginalLanguage pgtype.Text        `json:"original_language"`
	Country          pgtype.Text        `json:"country"`
	ImdbID           pgtype.Text        `json:"imdb_id"`
	TmdbID           pgtype.Int4        `json:"tmdb_id"`
	AverageRating    pgtype.Float4      `json:"average_rating"`
	RatingCount      pgtype.Int4        `json:"rating_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type MovieGenre struct {
	MovieID int32 `json:"movie_id"`
	GenreID int32 `json:"genre_id"`
}

type Notification struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Type      NotificationType   `json:"type"`
	Title     string             `json:"title"`
	Content   pgtype.Text        `json:"content"`
	IsRead    bool               `json:"is_read"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Person struct {
	ID         int32              `json:"id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	Biography  pgtype.Text        `json:"biography"`
	PhotoUrl   pgtype.Text        `json:"photo_url"`
	BirthDate  pgtype.Date        `json:"birth_date"`
	DeathDate  pgtype.Date        `json:"death_date"`
	Birthplace pgtype.Text        `json:"birthplace"`
	TmdbID     pgtype.Int4        `json:"tmdb_id"`
	ImdbID     pgtype.Text        `json:"imdb_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Rating struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	MovieID   int32              `json:"movie_id"`
	Score     int32              `json:"score"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Reaction struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	ReviewID  pgtype.Int4        `json:"review_id"`
	CommentID pgtype.Int4        `json:"comment_id"`
	Type      ReactionType       `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Review struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	MovieID   int32              `json:"movie_id"`
	Title     pgtype.Text        `json:"title"`
	Content   string             `json:"content"`
	LikeCount pgtype.Int4        `json:"like_count"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID           string             `json:"id"`
	UserID       int32              `json:"user_id"`
	RefreshToken pgtype.Text        `json:"refresh_token"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  pgtype.Text        `json:"display_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Bio          pgtype.Text        `json:"bio"`
	Role         Role               `json:"role"`
	Status       UserStatus         `json:"status"`
	IsVerified   bool               `json:"is_verified"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserStatusLog struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	OldStatus NullUserStatus     `json:"old_status"`
	NewStatus UserStatus         `json:"new_status"`
	Reason    pgtype.Text        `json:"reason"`
	ChangedBy pgtype.Int4        `json:"changed_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Watchlist struct {
	ID           int32              `json:"id"`
	UserID       int32              `json:"user_id"`
	MovieID      int32              `json:"movie_id"`
	Notes        pgtype.Text        `json:"notes"`
	RankPosition pgtype.Float4      `json:"rank_position"`
	WatchedAt    pgtype.Timestamptz `json:"watched_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
