// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advancedSearchMovies = `-- name: AdvancedSearchMovies :many
SELECT DISTINCT m.id, m.title, m.slug, m.overview, m.poster_url, m.backdrop_url, m.trailer_url, m.release_date, m.runtime, m.content_rating, m.original_language, m.country, m.imdb_id, m.tmdb_id, m.user_avg_rating, m.user_rating_count, m.created_at, m.updated_at, m.imdb_rating, m.rotten_tomatoes, m.metacritic_score, m.letterboxd_rating, m.rating_sum, m.landing_sort_score
FROM movies m
LEFT JOIN movie_genres mg ON mg.movie_id = m.id
WHERE
    -- Text search (optional)
    ($3::TEXT IS NULL OR m.title ILIKE '%' || $3::TEXT || '%')
    -- Genre filter (optional, array of genre IDs)
    AND ($4::INT[] IS NULL OR mg.genre_id = ANY($4::INT[]))
    -- Year range (optional)
    AND ($5::INT IS NULL OR EXTRACT(YEAR FROM m.release_date) >= $5::INT)
    AND ($6::INT IS NULL OR EXTRACT(YEAR FROM m.release_date) <= $6::INT)
    -- IMDB rating range (optional, scale 0-10)
    AND ($7::NUMERIC IS NULL OR m.imdb_rating >= $7::NUMERIC)
    AND ($8::NUMERIC IS NULL OR m.imdb_rating <= $8::NUMERIC)
    -- User rating range (optional, scale 1-10)
    AND ($9::REAL IS NULL OR m.user_avg_rating >= $9::REAL)
    AND ($10::REAL IS NULL OR m.user_avg_rating <= $10::REAL)
    -- Rotten Tomatoes range (optional, scale 0-100)
    AND ($11::INT IS NULL OR m.rotten_tomatoes >= $11::INT)
    AND ($12::INT IS NULL OR m.rotten_tomatoes <= $12::INT)
    -- Metacritic range (optional, scale 0-100)
    AND ($13::INT IS NULL OR m.metacritic_score >= $13::INT)
    AND ($14::INT IS NULL OR m.metacritic_score <= $14::INT)
ORDER BY
    CASE WHEN $15::TEXT = 'title_asc' THEN m.title END ASC,
    CASE WHEN $15::TEXT = 'title_desc' THEN m.title END DESC,
    CASE WHEN $15::TEXT = 'release_date_asc' THEN m.release_date END ASC,
    CASE WHEN $15::TEXT = 'release_date_desc' THEN m.release_date END DESC,
    CASE WHEN $15::TEXT = 'imdb_rating_asc' THEN m.imdb_rating END ASC,
    CASE WHEN $15::TEXT = 'imdb_rating_desc' THEN m.imdb_rating END DESC,
    CASE WHEN $15::TEXT = 'user_rating_asc' THEN m.user_avg_rating END ASC,
    CASE WHEN $15::TEXT = 'user_rating_desc' THEN m.user_avg_rating END DESC,
    CASE WHEN $15::TEXT = 'rotten_tomatoes_asc' THEN m.rotten_tomatoes END ASC,
    CASE WHEN $15::TEXT = 'rotten_tomatoes_desc' THEN m.rotten_tomatoes END DESC,
    CASE WHEN $15::TEXT = 'metacritic_asc' THEN m.metacritic_score END ASC,
    CASE WHEN $15::TEXT = 'metacritic_desc' THEN m.metacritic_score END DESC,
    m.imdb_rating DESC NULLS LAST,
    m.release_date DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type AdvancedSearchMoviesParams struct {
	Limit         int32          `json:"limit"`
	Offset        int32          `json:"offset"`
	Query         pgtype.Text    `json:"query"`
	GenreIds      []int32        `json:"genre_ids"`
	YearFrom      pgtype.Int4    `json:"year_from"`
	YearTo        pgtype.Int4    `json:"year_to"`
	ImdbMin       pgtype.Numeric `json:"imdb_min"`
	ImdbMax       pgtype.Numeric `json:"imdb_max"`
	UserRatingMin pgtype.Float4  `json:"user_rating_min"`
	UserRatingMax pgtype.Float4  `json:"user_rating_max"`
	RtMin         pgtype.Int4    `json:"rt_min"`
	RtMax         pgtype.Int4    `json:"rt_max"`
	MetacriticMin pgtype.Int4    `json:"metacritic_min"`
	MetacriticMax pgtype.Int4    `json:"metacritic_max"`
	SortBy        pgtype.Text    `json:"sort_by"`
}

// Advanced search with filters: query, genres, year range, rating range, sort
func (q *Queries) AdvancedSearchMovies(ctx context.Context, arg AdvancedSearchMoviesParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, advancedSearchMovies,
		arg.Limit,
		arg.Offset,
		arg.Query,
		arg.GenreIds,
		arg.YearFrom,
		arg.YearTo,
		arg.ImdbMin,
		arg.ImdbMax,
		arg.UserRatingMin,
		arg.UserRatingMax,
		arg.RtMin,
		arg.RtMax,
		arg.MetacriticMin,
		arg.MetacriticMax,
		arg.SortBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Overview,
			&i.PosterUrl,
			&i.BackdropUrl,
			&i.TrailerUrl,
			&i.ReleaseDate,
			&i.Runtime,
			&i.ContentRating,
			&i.OriginalLanguage,
			&i.Country,
			&i.ImdbID,
			&i.TmdbID,
			&i.UserAvgRating,
			&i.UserRatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImdbRating,
			&i.RottenTomatoes,
			&i.MetacriticScore,
			&i.LetterboxdRating,
			&i.RatingSum,
			&i.LandingSortScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAdvancedSearchMovies = `-- name: CountAdvancedSearchMovies :one
SELECT COUNT(DISTINCT m.id)::INT as total
FROM movies m
LEFT JOIN movie_genres mg ON mg.movie_id = m.id
WHERE
    ($1::TEXT IS NULL OR m.title ILIKE '%' || $1::TEXT || '%')
    AND ($2::INT[] IS NULL OR mg.genre_id = ANY($2::INT[]))
    AND ($3::INT IS NULL OR EXTRACT(YEAR FROM m.release_date) >= $3::INT)
    AND ($4::INT IS NULL OR EXTRACT(YEAR FROM m.release_date) <= $4::INT)
    AND ($5::NUMERIC IS NULL OR m.imdb_rating >= $5::NUMERIC)
    AND ($6::NUMERIC IS NULL OR m.imdb_rating <= $6::NUMERIC)
    AND ($7::REAL IS NULL OR m.user_avg_rating >= $7::REAL)
    AND ($8::REAL IS NULL OR m.user_avg_rating <= $8::REAL)
    AND ($9::INT IS NULL OR m.rotten_tomatoes >= $9::INT)
    AND ($10::INT IS NULL OR m.rotten_tomatoes <= $10::INT)
    AND ($11::INT IS NULL OR m.metacritic_score >= $11::INT)
    AND ($12::INT IS NULL OR m.metacritic_score <= $12::INT)
`

type CountAdvancedSearchMoviesParams struct {
	Query         pgtype.Text    `json:"query"`
	GenreIds      []int32        `json:"genre_ids"`
	YearFrom      pgtype.Int4    `json:"year_from"`
	YearTo        pgtype.Int4    `json:"year_to"`
	ImdbMin       pgtype.Numeric `json:"imdb_min"`
	ImdbMax       pgtype.Numeric `json:"imdb_max"`
	UserRatingMin pgtype.Float4  `json:"user_rating_min"`
	UserRatingMax pgtype.Float4  `json:"user_rating_max"`
	RtMin         pgtype.Int4    `json:"rt_min"`
	RtMax         pgtype.Int4    `json:"rt_max"`
	MetacriticMin pgtype.Int4    `json:"metacritic_min"`
	MetacriticMax pgtype.Int4    `json:"metacritic_max"`
}

// Count total results for advanced search (for pagination)
func (q *Queries) CountAdvancedSearchMovies(ctx context.Context, arg CountAdvancedSearchMoviesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAdvancedSearchMovies,
		arg.Query,
		arg.GenreIds,
		arg.YearFrom,
		arg.YearTo,
		arg.ImdbMin,
		arg.ImdbMax,
		arg.UserRatingMin,
		arg.UserRatingMax,
		arg.RtMin,
		arg.RtMax,
		arg.MetacriticMin,
		arg.MetacriticMax,
	)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const createCredit = `-- name: CreateCredit :exec

INSERT INTO credits (movie_id, person_id, department, role, character)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCreditParams struct {
	MovieID    int32       `json:"movie_id"`
	PersonID   int32       `json:"person_id"`
	Department Department  `json:"department"`
	Role       string      `json:"role"`
	Character  pgtype.Text `json:"character"`
}

// ============================================================
// CREDITS QUERIES
// ============================================================
// Create a link between a movie and a person (cast/crew)
func (q *Queries) CreateCredit(ctx context.Context, arg CreateCreditParams) error {
	_, err := q.db.Exec(ctx, createCredit,
		arg.MovieID,
		arg.PersonID,
		arg.Department,
		arg.Role,
		arg.Character,
	)
	return err
}

const createMovie = `-- name: CreateMovie :one

INSERT INTO movies (
    title, slug, overview, poster_url, release_date, runtime, 
    imdb_id, tmdb_id, imdb_rating, rotten_tomatoes, metacritic_score
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreateMovieParams struct {
	Title           string         `json:"title"`
	Slug            string         `json:"slug"`
	Overview        pgtype.Text    `json:"overview"`
	PosterUrl       pgtype.Text    `json:"poster_url"`
	ReleaseDate     pgtype.Date    `json:"release_date"`
	Runtime         pgtype.Int4    `json:"runtime"`
	ImdbID          pgtype.Text    `json:"imdb_id"`
	TmdbID          pgtype.Int4    `json:"tmdb_id"`
	ImdbRating      pgtype.Numeric `json:"imdb_rating"`
	RottenTomatoes  pgtype.Int4    `json:"rotten_tomatoes"`
	MetacriticScore pgtype.Int4    `json:"metacritic_score"`
}

// ============================================================
// MOVIES QUERIES
// ============================================================
// Create a new movie record with external ratings
func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (int32, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Title,
		arg.Slug,
		arg.Overview,
		arg.PosterUrl,
		arg.ReleaseDate,
		arg.Runtime,
		arg.ImdbID,
		arg.TmdbID,
		arg.ImdbRating,
		arg.RottenTomatoes,
		arg.MetacriticScore,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getMovieBySlug = `-- name: GetMovieBySlug :one
SELECT id, title, slug, overview, poster_url, backdrop_url, trailer_url, release_date, runtime, content_rating, original_language, country, imdb_id, tmdb_id, user_avg_rating, user_rating_count, created_at, updated_at, imdb_rating, rotten_tomatoes, metacritic_score, letterboxd_rating, rating_sum, landing_sort_score FROM movies
WHERE slug = $1 LIMIT 1
`

// Get a single movie by its unique slug
func (q *Queries) GetMovieBySlug(ctx context.Context, slug string) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieBySlug, slug)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Overview,
		&i.PosterUrl,
		&i.BackdropUrl,
		&i.TrailerUrl,
		&i.ReleaseDate,
		&i.Runtime,
		&i.ContentRating,
		&i.OriginalLanguage,
		&i.Country,
		&i.ImdbID,
		&i.TmdbID,
		&i.UserAvgRating,
		&i.UserRatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImdbRating,
		&i.RottenTomatoes,
		&i.MetacriticScore,
		&i.LetterboxdRating,
		&i.RatingSum,
		&i.LandingSortScore,
	)
	return i, err
}

const getMovieByTmdbID = `-- name: GetMovieByTmdbID :one
SELECT id, title, slug, overview, poster_url, backdrop_url, trailer_url, release_date, runtime, content_rating, original_language, country, imdb_id, tmdb_id, user_avg_rating, user_rating_count, created_at, updated_at, imdb_rating, rotten_tomatoes, metacritic_score, letterboxd_rating, rating_sum, landing_sort_score FROM movies WHERE tmdb_id = $1 LIMIT 1
`

// Get a movie by its TMDB ID
func (q *Queries) GetMovieByTmdbID(ctx context.Context, tmdbID pgtype.Int4) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieByTmdbID, tmdbID)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Overview,
		&i.PosterUrl,
		&i.BackdropUrl,
		&i.TrailerUrl,
		&i.ReleaseDate,
		&i.Runtime,
		&i.ContentRating,
		&i.OriginalLanguage,
		&i.Country,
		&i.ImdbID,
		&i.TmdbID,
		&i.UserAvgRating,
		&i.UserRatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImdbRating,
		&i.RottenTomatoes,
		&i.MetacriticScore,
		&i.LetterboxdRating,
		&i.RatingSum,
		&i.LandingSortScore,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT
    m.id,
    m.title,
    m.slug,
    m.poster_url,
    m.release_date,
    m.user_avg_rating,
    m.user_rating_count,
    m.imdb_rating,
    m.rotten_tomatoes,
    m.metacritic_score,
    m.landing_sort_score,
    COALESCE(d.directors, ARRAY[]::TEXT[]) AS directors
FROM movies m
LEFT JOIN LATERAL (
    SELECT ARRAY_AGG(DISTINCT p.name ORDER BY p.name) AS directors
    FROM credits c
    JOIN persons p ON p.id = c.person_id
    WHERE c.movie_id = m.id AND c.department = 'DIRECTING'
) d ON true
ORDER BY m.landing_sort_score DESC NULLS LAST, m.created_at DESC
LIMIT $1 OFFSET $2
`

type ListMoviesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMoviesRow struct {
	ID               int32          `json:"id"`
	Title            string         `json:"title"`
	Slug             string         `json:"slug"`
	PosterUrl        pgtype.Text    `json:"poster_url"`
	ReleaseDate      pgtype.Date    `json:"release_date"`
	UserAvgRating    pgtype.Float4  `json:"user_avg_rating"`
	UserRatingCount  pgtype.Int4    `json:"user_rating_count"`
	ImdbRating       pgtype.Numeric `json:"imdb_rating"`
	RottenTomatoes   pgtype.Int4    `json:"rotten_tomatoes"`
	MetacriticScore  pgtype.Int4    `json:"metacritic_score"`
	LandingSortScore pgtype.Numeric `json:"landing_sort_score"`
	Directors        interface{}    `json:"directors"`
}

// Get a paginated list of movies for landing-page cards, ordered by pre-computed weighted rating
func (q *Queries) ListMovies(ctx context.Context, arg ListMoviesParams) ([]ListMoviesRow, error) {
	rows, err := q.db.Query(ctx, listMovies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMoviesRow
	for rows.Next() {
		var i ListMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PosterUrl,
			&i.ReleaseDate,
			&i.UserAvgRating,
			&i.UserRatingCount,
			&i.ImdbRating,
			&i.RottenTomatoes,
			&i.MetacriticScore,
			&i.LandingSortScore,
			&i.Directors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMovies = `-- name: SearchMovies :many
SELECT id, title, slug, overview, poster_url, backdrop_url, trailer_url, release_date, runtime, content_rating, original_language, country, imdb_id, tmdb_id, user_avg_rating, user_rating_count, created_at, updated_at, imdb_rating, rotten_tomatoes, metacritic_score, letterboxd_rating, rating_sum, landing_sort_score FROM movies
WHERE title ILIKE '%' || $1 || '%' OR slug ILIKE '%' || $1 || '%'
ORDER BY imdb_rating DESC
LIMIT $2 OFFSET $3
`

type SearchMoviesParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// Simple search by title or slug
func (q *Queries) SearchMovies(ctx context.Context, arg SearchMoviesParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, searchMovies, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Overview,
			&i.PosterUrl,
			&i.BackdropUrl,
			&i.TrailerUrl,
			&i.ReleaseDate,
			&i.Runtime,
			&i.ContentRating,
			&i.OriginalLanguage,
			&i.Country,
			&i.ImdbID,
			&i.TmdbID,
			&i.UserAvgRating,
			&i.UserRatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImdbRating,
			&i.RottenTomatoes,
			&i.MetacriticScore,
			&i.LetterboxdRating,
			&i.RatingSum,
			&i.LandingSortScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCredit = `-- name: UpsertCredit :exec
INSERT INTO credits (movie_id, person_id, department, role, character, "order")
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT DO NOTHING
`

type UpsertCreditParams struct {
	MovieID    int32       `json:"movie_id"`
	PersonID   int32       `json:"person_id"`
	Department Department  `json:"department"`
	Role       string      `json:"role"`
	Character  pgtype.Text `json:"character"`
	Order      pgtype.Int4 `json:"order"`
}

// Create a credit or ignore if it already exists
func (q *Queries) UpsertCredit(ctx context.Context, arg UpsertCreditParams) error {
	_, err := q.db.Exec(ctx, upsertCredit,
		arg.MovieID,
		arg.PersonID,
		arg.Department,
		arg.Role,
		arg.Character,
		arg.Order,
	)
	return err
}

const upsertPerson = `-- name: UpsertPerson :one

INSERT INTO persons (name, slug)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertPersonParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// ============================================================
// PERSONS QUERIES
// ============================================================
// Insert a person or update their name if the slug already exists
func (q *Queries) UpsertPerson(ctx context.Context, arg UpsertPersonParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertPerson, arg.Name, arg.Slug)
	var id int32
	err := row.Scan(&id)
	return id, err
}
