// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredit = `-- name: CreateCredit :exec

INSERT INTO credits (movie_id, person_id, department, role, character)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCreditParams struct {
	MovieID    int32       `json:"movie_id"`
	PersonID   int32       `json:"person_id"`
	Department Department  `json:"department"`
	Role       string      `json:"role"`
	Character  pgtype.Text `json:"character"`
}

// ============================================================
// CREDITS QUERIES
// ============================================================
// Create a link between a movie and a person (cast/crew)
func (q *Queries) CreateCredit(ctx context.Context, arg CreateCreditParams) error {
	_, err := q.db.Exec(ctx, createCredit,
		arg.MovieID,
		arg.PersonID,
		arg.Department,
		arg.Role,
		arg.Character,
	)
	return err
}

const createMovie = `-- name: CreateMovie :one

INSERT INTO movies (
    title, slug, overview, poster_url, release_date, runtime, 
    imdb_id, tmdb_id, imdb_rating, rotten_tomatoes, metacritic_score
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreateMovieParams struct {
	Title           string         `json:"title"`
	Slug            string         `json:"slug"`
	Overview        pgtype.Text    `json:"overview"`
	PosterUrl       pgtype.Text    `json:"poster_url"`
	ReleaseDate     pgtype.Date    `json:"release_date"`
	Runtime         pgtype.Int4    `json:"runtime"`
	ImdbID          pgtype.Text    `json:"imdb_id"`
	TmdbID          pgtype.Int4    `json:"tmdb_id"`
	ImdbRating      pgtype.Numeric `json:"imdb_rating"`
	RottenTomatoes  pgtype.Int4    `json:"rotten_tomatoes"`
	MetacriticScore pgtype.Int4    `json:"metacritic_score"`
}

// ============================================================
// MOVIES QUERIES
// ============================================================
// Create a new movie record with external ratings
func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (int32, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Title,
		arg.Slug,
		arg.Overview,
		arg.PosterUrl,
		arg.ReleaseDate,
		arg.Runtime,
		arg.ImdbID,
		arg.TmdbID,
		arg.ImdbRating,
		arg.RottenTomatoes,
		arg.MetacriticScore,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getMovieBySlug = `-- name: GetMovieBySlug :one
SELECT id, title, slug, overview, poster_url, backdrop_url, trailer_url, release_date, runtime, content_rating, original_language, country, imdb_id, tmdb_id, user_avg_rating, user_rating_count, created_at, updated_at, imdb_rating, rotten_tomatoes, metacritic_score, letterboxd_rating FROM movies
WHERE slug = $1 LIMIT 1
`

// Get a single movie by its unique slug
func (q *Queries) GetMovieBySlug(ctx context.Context, slug string) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieBySlug, slug)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Overview,
		&i.PosterUrl,
		&i.BackdropUrl,
		&i.TrailerUrl,
		&i.ReleaseDate,
		&i.Runtime,
		&i.ContentRating,
		&i.OriginalLanguage,
		&i.Country,
		&i.ImdbID,
		&i.TmdbID,
		&i.UserAvgRating,
		&i.UserRatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImdbRating,
		&i.RottenTomatoes,
		&i.MetacriticScore,
		&i.LetterboxdRating,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, slug, overview, poster_url, backdrop_url, trailer_url, release_date, runtime, content_rating, original_language, country, imdb_id, tmdb_id, user_avg_rating, user_rating_count, created_at, updated_at, imdb_rating, rotten_tomatoes, metacritic_score, letterboxd_rating FROM movies
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMoviesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Get a paginated list of movies ordered by creation date
func (q *Queries) ListMovies(ctx context.Context, arg ListMoviesParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listMovies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Overview,
			&i.PosterUrl,
			&i.BackdropUrl,
			&i.TrailerUrl,
			&i.ReleaseDate,
			&i.Runtime,
			&i.ContentRating,
			&i.OriginalLanguage,
			&i.Country,
			&i.ImdbID,
			&i.TmdbID,
			&i.UserAvgRating,
			&i.UserRatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImdbRating,
			&i.RottenTomatoes,
			&i.MetacriticScore,
			&i.LetterboxdRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMovies = `-- name: SearchMovies :many
SELECT id, title, slug, overview, poster_url, backdrop_url, trailer_url, release_date, runtime, content_rating, original_language, country, imdb_id, tmdb_id, user_avg_rating, user_rating_count, created_at, updated_at, imdb_rating, rotten_tomatoes, metacritic_score, letterboxd_rating FROM movies
WHERE title ILIKE '%' || $1 || '%' OR slug ILIKE '%' || $1 || '%'
ORDER BY imdb_rating DESC
LIMIT $2 OFFSET $3
`

type SearchMoviesParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// Simple search by title or slug
func (q *Queries) SearchMovies(ctx context.Context, arg SearchMoviesParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, searchMovies, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Overview,
			&i.PosterUrl,
			&i.BackdropUrl,
			&i.TrailerUrl,
			&i.ReleaseDate,
			&i.Runtime,
			&i.ContentRating,
			&i.OriginalLanguage,
			&i.Country,
			&i.ImdbID,
			&i.TmdbID,
			&i.UserAvgRating,
			&i.UserRatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImdbRating,
			&i.RottenTomatoes,
			&i.MetacriticScore,
			&i.LetterboxdRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPerson = `-- name: UpsertPerson :one

INSERT INTO persons (name, slug)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertPersonParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// ============================================================
// PERSONS QUERIES
// ============================================================
// Insert a person or update their name if the slug already exists
func (q *Queries) UpsertPerson(ctx context.Context, arg UpsertPersonParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertPerson, arg.Name, arg.Slug)
	var id int32
	err := row.Scan(&id)
	return id, err
}
