// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::INT as count
FROM notifications
WHERE user_id = $1 AND is_read = FALSE
`

// Count unread notifications for a user
func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countUserNotifications = `-- name: CountUserNotifications :one
SELECT COUNT(*)::INT as count
FROM notifications
WHERE user_id = $1
`

// Count total notifications for a user
func (q *Queries) CountUserNotifications(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countUserNotifications, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, content, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, content, is_read, metadata, created_at
`

type CreateNotificationParams struct {
	UserID   int32            `json:"user_id"`
	Type     NotificationType `json:"type"`
	Title    string           `json:"title"`
	Content  pgtype.Text      `json:"content"`
	Metadata []byte           `json:"metadata"`
}

// Create a new notification
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.Metadata,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.IsRead,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllNotifications = `-- name: DeleteAllNotifications :exec
DELETE FROM notifications
WHERE user_id = $1
`

// Delete all notifications for a user
func (q *Queries) DeleteAllNotifications(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteAllNotifications, userID)
	return err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// Delete a specific notification
func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < $1
`

// Delete notifications older than specified date (cleanup)
func (q *Queries) DeleteOldNotifications(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications, createdAt)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, type, title, content, is_read, metadata, created_at FROM notifications
WHERE id = $1
`

// Get a specific notification
func (q *Queries) GetNotificationByID(ctx context.Context, id int32) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.IsRead,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadNotifications = `-- name: GetUnreadNotifications :many
SELECT id, user_id, type, title, content, is_read, metadata, created_at FROM notifications
WHERE user_id = $1 AND is_read = FALSE
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUnreadNotificationsParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Get unread notifications for a user
func (q *Queries) GetUnreadNotifications(ctx context.Context, arg GetUnreadNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getUnreadNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.IsRead,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT id, user_id, type, title, content, is_read, metadata, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserNotificationsParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Get all notifications for a user with pagination
func (q *Queries) GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getUserNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.IsRead,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE user_id = $1 AND is_read = FALSE
`

// Mark all notifications as read for a user
func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// Mark a specific notification as read
func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	return err
}
