// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRating = `-- name: DeleteRating :exec
DELETE FROM ratings
WHERE user_id = $1 AND movie_id = $2
`

type DeleteRatingParams struct {
	UserID  pgtype.Int4 `json:"user_id"`
	MovieID int32       `json:"movie_id"`
}

func (q *Queries) DeleteRating(ctx context.Context, arg DeleteRatingParams) error {
	_, err := q.db.Exec(ctx, deleteRating, arg.UserID, arg.MovieID)
	return err
}

const getMovieByID = `-- name: GetMovieByID :one
SELECT id, title, slug, overview, poster_url, backdrop_url, trailer_url, release_date, runtime, content_rating, original_language, country, imdb_id, tmdb_id, user_avg_rating, user_rating_count, created_at, updated_at, imdb_rating, rotten_tomatoes, metacritic_score, letterboxd_rating, rating_sum, landing_sort_score FROM movies WHERE id = $1
`

func (q *Queries) GetMovieByID(ctx context.Context, id int32) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieByID, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Overview,
		&i.PosterUrl,
		&i.BackdropUrl,
		&i.TrailerUrl,
		&i.ReleaseDate,
		&i.Runtime,
		&i.ContentRating,
		&i.OriginalLanguage,
		&i.Country,
		&i.ImdbID,
		&i.TmdbID,
		&i.UserAvgRating,
		&i.UserRatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImdbRating,
		&i.RottenTomatoes,
		&i.MetacriticScore,
		&i.LetterboxdRating,
		&i.RatingSum,
		&i.LandingSortScore,
	)
	return i, err
}

const getMovieRatings = `-- name: GetMovieRatings :many
SELECT
    r.id, r.user_id, r.movie_id, r.score, r.created_at, r.updated_at,
    u.username,
    u.display_name,
    u.avatar_url
FROM ratings r
JOIN users u ON u.id = r.user_id
WHERE r.movie_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMovieRatingsParams struct {
	MovieID int32 `json:"movie_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type GetMovieRatingsRow struct {
	ID          int64              `json:"id"`
	UserID      pgtype.Int4        `json:"user_id"`
	MovieID     int32              `json:"movie_id"`
	Score       int32              `json:"score"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetMovieRatings(ctx context.Context, arg GetMovieRatingsParams) ([]GetMovieRatingsRow, error) {
	rows, err := q.db.Query(ctx, getMovieRatings, arg.MovieID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovieRatingsRow
	for rows.Next() {
		var i GetMovieRatingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MovieID,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRatingForMovie = `-- name: GetUserRatingForMovie :one
SELECT id, user_id, movie_id, score, created_at, updated_at FROM ratings
WHERE user_id = $1 AND movie_id = $2
`

type GetUserRatingForMovieParams struct {
	UserID  pgtype.Int4 `json:"user_id"`
	MovieID int32       `json:"movie_id"`
}

func (q *Queries) GetUserRatingForMovie(ctx context.Context, arg GetUserRatingForMovieParams) (Rating, error) {
	row := q.db.QueryRow(ctx, getUserRatingForMovie, arg.UserID, arg.MovieID)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRatings = `-- name: GetUserRatings :many
SELECT
    r.id, r.user_id, r.movie_id, r.score, r.created_at, r.updated_at,
    m.title,
    m.slug,
    m.poster_url
FROM ratings r
JOIN movies m ON m.id = r.movie_id
WHERE r.user_id = $1
ORDER BY r.updated_at DESC
LIMIT $2 OFFSET $3
`

type GetUserRatingsParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetUserRatingsRow struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int4        `json:"user_id"`
	MovieID   int32              `json:"movie_id"`
	Score     int32              `json:"score"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Title     string             `json:"title"`
	Slug      string             `json:"slug"`
	PosterUrl pgtype.Text        `json:"poster_url"`
}

func (q *Queries) GetUserRatings(ctx context.Context, arg GetUserRatingsParams) ([]GetUserRatingsRow, error) {
	rows, err := q.db.Query(ctx, getUserRatings, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRatingsRow
	for rows.Next() {
		var i GetUserRatingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MovieID,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Slug,
			&i.PosterUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovieRatingStats = `-- name: UpdateMovieRatingStats :exec
UPDATE movies
SET
    user_avg_rating = (SELECT AVG(r.score)::REAL FROM ratings r WHERE r.movie_id = $1),
    user_rating_count = (SELECT COUNT(*)::INT FROM ratings r WHERE r.movie_id = $1),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateMovieRatingStats(ctx context.Context, movieID int32) error {
	_, err := q.db.Exec(ctx, updateMovieRatingStats, movieID)
	return err
}

const upsertRating = `-- name: UpsertRating :one
INSERT INTO ratings (user_id, movie_id, score)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, movie_id)
DO UPDATE SET score = EXCLUDED.score, updated_at = NOW()
RETURNING id, user_id, movie_id, score, created_at, updated_at
`

type UpsertRatingParams struct {
	UserID  pgtype.Int4 `json:"user_id"`
	MovieID int32       `json:"movie_id"`
	Score   int32       `json:"score"`
}

func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, upsertRating, arg.UserID, arg.MovieID, arg.Score)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
