// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token, user_agent, ip_address, expires_at)
VALUES ($1, 'sha256:' || encode(digest($2, 'sha256'), 'hex'), $3, $4, $5)
RETURNING id, user_id, refresh_token, user_agent, ip_address, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    int32              `json:"user_id"`
	Digest    string             `json:"digest"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress pgtype.Text        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.Digest,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByRefreshToken = `-- name: DeleteSessionByRefreshToken :exec
DELETE FROM sessions
WHERE refresh_token = 'sha256:' || encode(digest($1, 'sha256'), 'hex')
`

func (q *Queries) DeleteSessionByRefreshToken(ctx context.Context, digest string) error {
	_, err := q.db.Exec(ctx, deleteSessionByRefreshToken, digest)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token, user_agent, ip_address, expires_at, created_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, refresh_token, user_agent, ip_address, expires_at, created_at FROM sessions
WHERE refresh_token = 'sha256:' || encode(digest($1, 'sha256'), 'hex')
LIMIT 1
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, digest string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, digest)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions 
SET refresh_token = 'sha256:' || encode(digest($2, 'sha256'), 'hex'), expires_at = $3 
WHERE id = $1
`

type UpdateSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	Digest    string             `json:"digest"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession, arg.ID, arg.Digest, arg.ExpiresAt)
	return err
}
