// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToWatchlist = `-- name: AddToWatchlist :one
INSERT INTO watchlists (user_id, movie_id, notes, rank_position)
VALUES ($1, $2, $3, COALESCE($4, (SELECT COALESCE(MAX(rank_position), 0) + 1 FROM watchlists WHERE user_id = $1)))
RETURNING id, user_id, movie_id, notes, rank_position, watched_at, created_at
`

type AddToWatchlistParams struct {
	UserID  int32       `json:"user_id"`
	MovieID int32       `json:"movie_id"`
	Notes   pgtype.Text `json:"notes"`
	Column4 interface{} `json:"column_4"`
}

func (q *Queries) AddToWatchlist(ctx context.Context, arg AddToWatchlistParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, addToWatchlist,
		arg.UserID,
		arg.MovieID,
		arg.Notes,
		arg.Column4,
	)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Notes,
		&i.RankPosition,
		&i.WatchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countUserWatchlist = `-- name: CountUserWatchlist :one
SELECT
    COUNT(*) FILTER (WHERE watched_at IS NULL)::INT as unwatched,
    COUNT(*) FILTER (WHERE watched_at IS NOT NULL)::INT as watched,
    COUNT(*)::INT as total
FROM watchlists
WHERE user_id = $1
`

type CountUserWatchlistRow struct {
	Unwatched int32 `json:"unwatched"`
	Watched   int32 `json:"watched"`
	Total     int32 `json:"total"`
}

func (q *Queries) CountUserWatchlist(ctx context.Context, userID int32) (CountUserWatchlistRow, error) {
	row := q.db.QueryRow(ctx, countUserWatchlist, userID)
	var i CountUserWatchlistRow
	err := row.Scan(&i.Unwatched, &i.Watched, &i.Total)
	return i, err
}

const getUserWatchlist = `-- name: GetUserWatchlist :many
SELECT
    w.id, w.user_id, w.movie_id, w.notes, w.rank_position, w.watched_at, w.created_at,
    m.title,
    m.slug,
    m.poster_url,
    m.release_date,
    m.runtime,
    m.user_avg_rating
FROM watchlists w
JOIN movies m ON m.id = w.movie_id
WHERE w.user_id = $1
  AND ($2::bool IS FALSE OR w.watched_at IS NULL)
  AND ($3::bool IS FALSE OR w.watched_at IS NOT NULL)
ORDER BY w.rank_position ASC
LIMIT $4 OFFSET $5
`

type GetUserWatchlistParams struct {
	UserID  int32 `json:"user_id"`
	Column2 bool  `json:"column_2"`
	Column3 bool  `json:"column_3"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type GetUserWatchlistRow struct {
	ID            int32              `json:"id"`
	UserID        int32              `json:"user_id"`
	MovieID       int32              `json:"movie_id"`
	Notes         pgtype.Text        `json:"notes"`
	RankPosition  pgtype.Float4      `json:"rank_position"`
	WatchedAt     pgtype.Timestamptz `json:"watched_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	PosterUrl     pgtype.Text        `json:"poster_url"`
	ReleaseDate   pgtype.Date        `json:"release_date"`
	Runtime       pgtype.Int4        `json:"runtime"`
	UserAvgRating pgtype.Float4      `json:"user_avg_rating"`
}

func (q *Queries) GetUserWatchlist(ctx context.Context, arg GetUserWatchlistParams) ([]GetUserWatchlistRow, error) {
	rows, err := q.db.Query(ctx, getUserWatchlist,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWatchlistRow
	for rows.Next() {
		var i GetUserWatchlistRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MovieID,
			&i.Notes,
			&i.RankPosition,
			&i.WatchedAt,
			&i.CreatedAt,
			&i.Title,
			&i.Slug,
			&i.PosterUrl,
			&i.ReleaseDate,
			&i.Runtime,
			&i.UserAvgRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchlistEntry = `-- name: GetWatchlistEntry :one
SELECT id, user_id, movie_id, notes, rank_position, watched_at, created_at FROM watchlists
WHERE user_id = $1 AND movie_id = $2
`

type GetWatchlistEntryParams struct {
	UserID  int32 `json:"user_id"`
	MovieID int32 `json:"movie_id"`
}

func (q *Queries) GetWatchlistEntry(ctx context.Context, arg GetWatchlistEntryParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, getWatchlistEntry, arg.UserID, arg.MovieID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Notes,
		&i.RankPosition,
		&i.WatchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const isInWatchlist = `-- name: IsInWatchlist :one
SELECT EXISTS(
    SELECT 1 FROM watchlists
    WHERE user_id = $1 AND movie_id = $2
) as in_watchlist
`

type IsInWatchlistParams struct {
	UserID  int32 `json:"user_id"`
	MovieID int32 `json:"movie_id"`
}

func (q *Queries) IsInWatchlist(ctx context.Context, arg IsInWatchlistParams) (bool, error) {
	row := q.db.QueryRow(ctx, isInWatchlist, arg.UserID, arg.MovieID)
	var in_watchlist bool
	err := row.Scan(&in_watchlist)
	return in_watchlist, err
}

const markAsUnwatched = `-- name: MarkAsUnwatched :one
UPDATE watchlists
SET watched_at = NULL
WHERE user_id = $1 AND movie_id = $2
RETURNING id, user_id, movie_id, notes, rank_position, watched_at, created_at
`

type MarkAsUnwatchedParams struct {
	UserID  int32 `json:"user_id"`
	MovieID int32 `json:"movie_id"`
}

func (q *Queries) MarkAsUnwatched(ctx context.Context, arg MarkAsUnwatchedParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, markAsUnwatched, arg.UserID, arg.MovieID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Notes,
		&i.RankPosition,
		&i.WatchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markAsWatched = `-- name: MarkAsWatched :one
UPDATE watchlists
SET watched_at = NOW()
WHERE user_id = $1 AND movie_id = $2
RETURNING id, user_id, movie_id, notes, rank_position, watched_at, created_at
`

type MarkAsWatchedParams struct {
	UserID  int32 `json:"user_id"`
	MovieID int32 `json:"movie_id"`
}

func (q *Queries) MarkAsWatched(ctx context.Context, arg MarkAsWatchedParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, markAsWatched, arg.UserID, arg.MovieID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Notes,
		&i.RankPosition,
		&i.WatchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const removeFromWatchlist = `-- name: RemoveFromWatchlist :exec
DELETE FROM watchlists
WHERE user_id = $1 AND movie_id = $2
`

type RemoveFromWatchlistParams struct {
	UserID  int32 `json:"user_id"`
	MovieID int32 `json:"movie_id"`
}

func (q *Queries) RemoveFromWatchlist(ctx context.Context, arg RemoveFromWatchlistParams) error {
	_, err := q.db.Exec(ctx, removeFromWatchlist, arg.UserID, arg.MovieID)
	return err
}

const reorderWatchlistItem = `-- name: ReorderWatchlistItem :exec
UPDATE watchlists
SET rank_position = $3
WHERE user_id = $1 AND movie_id = $2
`

type ReorderWatchlistItemParams struct {
	UserID       int32         `json:"user_id"`
	MovieID      int32         `json:"movie_id"`
	RankPosition pgtype.Float4 `json:"rank_position"`
}

func (q *Queries) ReorderWatchlistItem(ctx context.Context, arg ReorderWatchlistItemParams) error {
	_, err := q.db.Exec(ctx, reorderWatchlistItem, arg.UserID, arg.MovieID, arg.RankPosition)
	return err
}

const updateWatchlistEntry = `-- name: UpdateWatchlistEntry :one
UPDATE watchlists
SET
    notes = COALESCE($3, notes),
    rank_position = COALESCE($4, rank_position),
    updated_at = NOW()
WHERE user_id = $1 AND movie_id = $2
RETURNING id, user_id, movie_id, notes, rank_position, watched_at, created_at
`

type UpdateWatchlistEntryParams struct {
	UserID       int32         `json:"user_id"`
	MovieID      int32         `json:"movie_id"`
	Notes        pgtype.Text   `json:"notes"`
	RankPosition pgtype.Float4 `json:"rank_position"`
}

func (q *Queries) UpdateWatchlistEntry(ctx context.Context, arg UpdateWatchlistEntryParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, updateWatchlistEntry,
		arg.UserID,
		arg.MovieID,
		arg.Notes,
		arg.RankPosition,
	)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Notes,
		&i.RankPosition,
		&i.WatchedAt,
		&i.CreatedAt,
	)
	return i, err
}
